# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Pocket-Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pocket-Chat
  pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :tag => '3.0.0'
  pod 'MessageInputBar'
  pod 'PocketSwift'
 

  target 'Pocket-ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
